-- =========================================================================
-- Phlo AI Ops - company directory seed (138 people, per HR employee list 2026-07-17)
-- Run AFTER people_directory_migration.sql.
-- Idempotent - re-running updates display_name/title/team/start_date for
-- any rows whose canonical email already exists.
-- =========================================================================

insert into public.people (email, display_name, title, team, start_date) values
  ('adam.hunter@wearephlo.com',           'Adam Hunter',                 'Chief Executive Officer',                  'Executive',          '2019-01-14'),
  ('alistair.murray@wearephlo.com',       'Alistair Murray',             'Chief Operating Officer',                  'Executive',          '2023-05-15'),
  ('allison.jackson@wearephlo.com',       'Allison Jackson',             'Senior Pharmacy Technician',               'Dispensary',         '2023-04-01'),
  ('andrew.mccappin@wearephlo.com',       'Andrew Magnus McCappin',      'Senior Motion Designer',                   'Digital Marketing',  '2020-03-01'),
  ('andrew.wallace@wearephlo.com',        'Andrew David Wallace',        'Software Engineer 1',                      'Technology',         '2024-03-04'),
  ('aneeza.zafar@wearephlo.com',          'Aneeza Zafar',                'Pharmacy Dispenser',                       'Dispensary',         '2023-04-01'),
  ('anthony.gangel@wearephlo.com',        'Anthony Robert Gangel',       'Senior Software Engineer 2',               'Technology',         '2022-01-06'),
  ('aqsa.zahoor@wearephlo.com',           'Aqsa Zahoor',                 'Test Manager',                             'Product',            '2026-03-09'),
  ('ashley.hearton@wearephlo.com',        'Ashley Kate Hearton',         'Senior Market Researcher',                 'Product Marketing',  '2020-09-01'),
  ('assean.sheikh@wearephlo.com',         'Assean Sheikh',               'Chief Marketing Officer',                  'Executive',          '2026-04-01'),
  ('barry.williams@wearephlo.com',        'Barry John Williams',         'Engineering Manager 2',                    'Technology',         '2021-11-15'),
  ('bijal.patel@wearephlo.com',           'Bijal Patel',                 'Senior Prescribing Pharmacist',            'Clinical',           '2025-06-30'),
  ('brian.grassie@wearephlo.com',         'Brian Grassie',               'Head of Digital Marketing',                'Digital Marketing',  '2020-05-11'),
  ('callan.wilson@wearephlo.com',         'Callan Wilson',               'Marketing Intelligence Intern',            'Product Marketing',  null),
  ('calum.watson@wearephlo.com',          'Calum Watson',                'UX Designer',                              'Design',             '2023-06-19'),
  ('carrieann.mcaulay@wearephlo.com',     'Carrieann McAulay',           'Lead Patient Care Advisor',                'Patient Care',       '2021-04-19'),
  ('carson.cheung@wearephlo.com',         'Carson Cheung',               'Senior Software Engineer 2',               'Technology',         '2022-08-01'),
  ('casey.long@wearephlo.com',            'Casey Long',                  'Operational Efficiency Product Intern',    'Technology',         null),
  ('chandni.sehgal@wearephlo.com',        'Chandni (Nikki) Sehgal',      'Remote Pharmacy Technician',               'Clinical',           '2025-03-10'),
  ('chris.cullen@wearephlo.com',          'Christopher Cullen',          'Chief Financial Officer',                    'Executive',          '2023-05-01'),
  ('chris.taylor@wearephlo.com',          'Christopher Taylor',          'Design Director',                          'Design',             '2022-01-03'),
  ('christopher.campbell@wearephlo.com',  'Christopher Campbell',        'Analytics Engineer',                       'Data & Automation',  '2024-07-01'),
  ('chung.hin-yip@wearephlo.com',         'Chung Hin Yip',               'Fulfilment Operative',                     'Fulfilment',         '2025-08-25'),
  ('colette.kinnaird@wearephlo.com',      'Colette Kinnaird',            'Senior Software Engineer 1',               'Technology',         '2021-09-01'),
  ('craig.glover@wearephlo.com',          'Craig William Glover',        'Senior Graphic Designer',                  'Digital Marketing',  '2021-03-01'),
  ('daniel.moore@wearephlo.com',          'Daniel Moore',                'Dispensary Manager',                       'Dispensary',         '2025-12-01'),
  ('danielle.findlay@wearephlo.com',      'Danielle Findlay',            'Senior CRM Executive',                     'Product Marketing',  '2025-01-06'),
  ('david.anderson@wearephlo.com',        'David Anderson',              'Head of Finance',                          'Finance',            '2025-10-20'),
  ('dennis.ouko@wearephlo.com',           'Dennis Ouko',                 'Superintendent Pharmacist',                'Governance',         '2023-04-01'),
  ('dhrsita.jethwa@wearephlo.com',        'Dhrsita Jethwa',              'Patient Services Pharmacist',              'Patient Services',   '2022-07-04'),
  ('dylan.mooney@wearephlo.com',          'Dylan Mooney',                'Senior Software Engineer 1',               'Technology',         '2024-07-01'),
  ('eilidh.mackay@wearephlo.com',         'Eilidh Mackay',               'Lead UX Designer',                         'Design',             '2022-04-11'),
  ('ellen.mclean@wearephlo.com',          'Ellen Louise McLean',         'Senior Graphic Designer',                  'Digital Marketing',  '2020-11-02'),
  ('ermina.toma@wearephlo.com',           'Ermina Toma',                 'Head of Fulfilment',                       'Fulfilment',         '2024-07-01'),
  ('eva.luckhiram@wearephlo.com',         'Eva Luckhiram',               'Head of Product',                          'Product',            '2020-10-01'),
  ('foo-wai.siu@wearephlo.com',           'Foo Wai Siu',                 'Fulfilment Operative',                     'Fulfilment',         null),
  ('georgina.thomas@wearephlo.com',       'Georgina Marie Thomas',       'Patient Services Dispenser',               'Patient Services',   '2022-10-24'),
  ('govinder.chadda@wearephlo.com',       'Govinder Chadda',             'Prescribing Pharmacist',                   'Clinical',           '2025-09-01'),
  ('grant.robinson@wearephlo.com',        'Grant Robinson',              'Digital Marketing Executive',              'Digital Marketing',  '2026-01-05'),
  ('hannah.josiah@wearephlo.com',         'Hannah Josiah',               'Prescribing Pharmacist',                   'Clinical',           '2024-12-16'),
  ('hannah.temple@wearephlo.com',         'Hannah Temple',               'Senior UX Designer',                       'Design',             '2021-11-15'),
  ('harvinder.gill@wearephlo.com',        'Harvinder Singh Gill',        'Prescribing Pharmacist',                   'Clinical',           '2024-12-04'),
  ('haseeb.hamid@wearephlo.com',          'Haseeb Hamid',                'AI Implementation Specialist',             'Technology',         '2026-04-27'),
  ('hazel.shore@wearephlo.com',           'Hazel Shore',                 'Obesity Specialist Dietitian',             'Clinical',           '2024-07-02'),
  ('heather.lamont@wearephlo.com',        'Heather Lamont',              'Product Tester',                           'Product',            '2023-06-26'),
  ('heather.young@wearephlo.com',         'Heather Young',               'Senior Product Marketing Manager',         'Product Marketing',  '2024-01-15'),
  ('helen.clarke@wearephlo.com',          'Helen Clarke',                'Pharmacy Dispenser',                       'Dispensary',         '2024-02-01'),
  ('ian.mackinnon@wearephlo.com',         'Ian Dugald MacKinnon',        'Senior Software Engineer 1',               'Technology',         '2023-09-04'),
  ('ilenia.vezil@wearephlo.com',          'Ilenia Vezil',                'Performance Marketing Specialist',         'Digital Marketing',  '2023-10-02'),
  ('ingrid.maughan@wearephlo.com',        'Ingrid Maughan',              'Senior Patient Care Advisor',              'Patient Care',       '2022-04-11'),
  ('iram.ahmed@wearephlo.com',            'Iram Ahmed',                  'Prescribing Pharmacist',                   'Clinical',           '2023-04-01'),
  ('ismaa.yusaf@wearephlo.com',           'Ismaa Yusaf',                 'Senior Pharmacy Dispenser',                'Dispensary',         '2022-04-25'),
  ('jacqueline.mcgeachie@wearephlo.com',  'Jacqueline McGeachie',        'Finance Assistant',                        'Finance',            '2024-12-09'),
  ('jade.macfarlane@wearephlo.com',       'Jade Macfarlane',             'Lead UX Designer',                         'Design',             '2021-11-01'),
  ('james.maciver@wearephlo.com',         'James Maciver',               'Chief Technology Officer',                 'Executive',          '2019-09-02'),
  ('jamie.macdonald@wearephlo.com',       'Jamie MacDonald',             'Head of Engineering',                      'Technology',         '2019-10-28'),
  ('japhia.saju@wearephlo.com',           'Japhia Saju',                 'Senior Pharmacy Dispenser',                'Dispensary',         '2024-04-02'),
  ('jasmine.mundy@wearephlo.com',         'Jasmine Mundy',               'Patient Care Advisor',                     'Patient Care',       null),
  ('jason.mcgibbon@wearephlo.com',        'Jason McGibbon',              'Non Executive Director',                   'Executive',          null),
  ('jaya.shen@wearephlo.com',             'Jaya Shen',                   'Fulfilment Operative',                     'Fulfilment',         '2024-10-07'),
  ('jessica.pitt@wearephlo.com',          'Jessica Pitt',                'Remote Pharmacy Technician',               'Clinical',           '2025-02-05'),
  ('joanna.hastie@wearephlo.com',         'Joanna Buchanan',             'Senior Product Owner',                     'Product',            '2021-09-27'),
  ('john.kennedy@wearephlo.com',          'John Kennedy',                'Software Engineer 2',                      'Technology',         '2023-12-04'),
  ('john.martin@wearephlo.com',           'John Martin',                 'Procurement Manager',                      'Dispensary',         '2024-06-12'),
  ('jonathan.forbes@wearephlo.com',       'Jonathan Forbes',             'Chief Data & Automation Officer',          'Executive',          '2019-06-24'),
  ('judith.borland@wearephlo.com',        'Judith Ann Borland',          'Performance Marketing Specialist',         'Digital Marketing',  '2022-03-21'),
  ('julien.maze@wearephlo.com',           'Julien Mazé',                 'Engineering Manager 1',                    'Technology',         '2022-01-24'),
  ('katie.devlin@wearephlo.com',          'Katie Devlin',                'Patient Care Advisor',                     'Patient Care',       '2025-10-13'),
  ('keertan.kaur@wearephlo.com',          'Keertan Kaur',                'Prescribing Pharmacist',                   'Clinical',           '2025-01-27'),
  ('kerri.ashe@wearephlo.com',            'Kerri Gibson',                'Patient Care Advisor',                     'Patient Care',       '2023-07-31'),
  ('kevin.odonnell@wearephlo.com',        'Kevin O''Donnell',            'Retention & Lifecycle Marketing Manager',  'Product Marketing',  null),
  ('khusboo.patel@wearephlo.com',         'Khusboo Patel',              'Head of Clinical Product',                 'Clinical Product',   '2026-01-05'),
  ('kyla.godwin@wearephlo.com',           'Kyla Godwin',                 'Pharmacy Dispenser',                       'Dispensary',         '2025-01-27'),
  ('laura.hannar@wearephlo.com',          'Laura Hannar',                'Remote Pharmacy Technician',               'Clinical',           '2025-08-04'),
  ('lauren.hobbs@wearephlo.com',          'Lauren Philippa Hobbs',       'Prescribing Pharmacist',                   'Clinical',           '2025-11-03'),
  ('lauren.nicholson@wearephlo.com',      'Lauren Nicholson',            'Chief of Staff',                           'Executive',          '2019-11-27'),
  ('leah.mceleny@wearephlo.com',          'Leah Sarah McEleny',          'Senior Patient Care Advisor',              'Patient Care',       '2023-05-30'),
  ('lorena.banchonmeza@wearephlo.com',    'Silvana Banchon Meza',        'Fulfilment Operative',                     'Fulfilment',         null),
  ('lucy.drennan@wearephlo.com',          'Lucy Drennan',                'Senior Social Media & Content Executive',  'Product Marketing',  '2021-06-07'),
  ('mairead.quigley@wearephlo.com',       'Elizabeth Quigley',           'Head of Product Marketing',                'Product Marketing',  '2020-09-01'),
  ('mark.maclellan@wearephlo.com',        'Mark MacLellan',              'Software Engineer 2',                      'Technology',         '2023-07-10'),
  ('mason.halls@wearephlo.com',           'Mason Halls',                 'Senior Operations Lead',                   'Dispensary',         '2020-09-28'),
  ('matteo.fusillo@wearephlo.com',        'Matteo Fusillo',              'Senior Software Engineer 1',               'Technology',         '2021-04-26'),
  ('michael.mann@wearephlo.com',          'Michael Mann',                'Patient Care Manager',                     'Patient Care',       '2025-03-31'),
  ('michael.mcculloch@wearephlo.com',     'Michael McCulloch',           'Principal Software Engineer 1',            'Technology',         '2021-02-08'),
  ('michael.sweeney@wearephlo.com',       'Michael Sweeney',             'Management Accountant',                    'Finance',            '2026-03-30'),
  ('michelle.wilson@wearephlo.com',       'Michelle Wilson',             'Patient Care Advisor',                     'Patient Care',       '2024-05-20'),
  ('mohammad.hussain@wearephlo.com',      'Mohammad Hussain',            'Senior Goods In Operative',                'Fulfilment',         '2025-02-03'),
  ('nakita.birmingham@wearephlo.com',     'Nakita Birmingham',           'Pharmacy Dispenser',                       'Dispensary',         '2024-10-21'),
  ('natasha.buchanan@wearephlo.com',      'Natasha Buchanan',            'Junior Digital Marketing Executive',       'Digital Marketing',  '2024-11-11'),
  ('natasha.mayor@wearephlo.com',         'Natasha Mayor',               'Patient Care Advisor',                     'Patient Care',       '2023-04-01'),
  ('nazmus.ahmed@wearephlo.com',          'Nazmus Ahmed',                'Prescribing Pharmacist',                   'Clinical',           '2025-11-03'),
  ('neal.archbold@wearephlo.com',         'Neal Archbold',               'Chief Business Development Officer',       'Executive',          '2024-03-04'),
  ('nicola.robertson@wearephlo.com',      'Nicola Robertson',            'Lead Product Owner',                       'Product',            '2023-09-25'),
  ('nishita.patel@wearephlo.com',         'Nishita Patel',               'Prescribing Pharmacist',                   'Clinical',           '2025-09-01'),
  ('owen.oneill@wearephlo.com',           'Owen O''Neill',               'Fulfilment Manager',                       'Fulfilment',         '2025-03-31'),
  ('pamela.looper@wearephlo.com',         'Pamela Looper',               'Software Engineer 2',                      'Technology',         '2022-08-01'),
  ('paulina.bzdziuch@wearephlo.com',      'Paulina Bzdziuch',            'Patient Services Dispenser',               'Patient Services',   '2021-11-15'),
  ('pavan.kular@wearephlo.com',           'Pavandeep Kular',             'Patient Services Pharmacist',              'Patient Services',   '2021-07-05'),
  ('poonam.thakkar@wearephlo.com',        'Poonam Thakkar',              'Prescribing Pharmacist',                   'Clinical',           '2024-05-22'),
  ('prabhjit.jassal@wearephlo.com',       'Prabhjit Jassal',             'Head of Patient Services',                 'Patient Services',   '2019-02-18'),
  ('pritesh.dodhia@wearephlo.com',        'Pritesh Dodhia',              'Head of Operations',                       'Dispensary',         '2019-10-07'),
  ('pryesh.mistry@wearephlo.com',         'Pryesh Mistry',               'Lead Prescribing Pharmacist',              'Clinical',           '2024-11-18'),
  ('rachael.blair@wearephlo.com',         'Rachael Blair',               'Senior People Advisor',                    'People',             '2022-04-25'),
  ('rachal.smith@wearephlo.com',          'Rachal Smith',                'Senior Software Engineer 1',               'Technology',         '2024-07-01'),
  ('rachel.barker@wearephlo.com',         'Rachel Ann Barker',           'Product Tester',                           'Product',            '2022-03-28'),
  ('rebecca.ross@wearephlo.com',          'Rebecca Ross',                'Remote Pharmacy Technician',               'Clinical',           '2023-04-01'),
  ('ricky.wai-ki-shan@wearephlo.com',     'Wai Ki Shan',                 'Fulfilment Operative',                     'Fulfilment',         '2025-12-01'),
  ('ross.donohoe@wearephlo.com',          'Ross Donohoe',                'Principal Software Engineer 1',            'Technology',         '2022-06-20'),
  ('ross.strachan@wearephlo.com',         'Ross Strachan',               'Principal Data Analyst',                   'Data & Automation',  '2024-07-01'),
  ('ruta.araya@wearephlo.com',            'Ruta Araya',                  'Pharmacist',                               'Dispensary',         '2025-10-29'),
  ('ryan.spiers@wearephlo.com',           'Ryan Spiers',                 'Senior UX Designer',                       'Design',             '2021-11-01'),
  ('sadia.sultana@wearephlo.com',         'Sadia Sultana',               'Pharmacist',                               'Dispensary',         '2025-12-08'),
  ('safa.jilani@wearephlo.com',           'Safa Jilani',                 'Pharmacy Dispenser',                       'Dispensary',         '2024-07-15'),
  ('saimah.uddin@wearephlo.com',          'Saimah Uddin',                'Prescribing Pharmacist',                   'Clinical',           '2025-02-03'),
  ('sami.colbourne@wearephlo.com',        'Sami Colbourne',              'Pharmacist',                               'Dispensary',         null),
  ('sara.deatcher@wearephlo.com',         'Sara Deatcher',               'Patient Care Advisor',                     'Patient Care',       '2024-11-25'),
  ('sarah.perry@wearephlo.com',           'Sarah Perry',                 'Senior Fulfilment Operative',              'Fulfilment',         '2024-12-02'),
  ('sean.clark@wearephlo.com',            'Sean Clark',                  'Software Engineer 2',                      'Technology',         '2024-03-18'),
  ('sean.mcmenemy@wearephlo.com',         'Sean Michael McMenemy',       'Patient Care Advisor',                     'Patient Care',       '2026-04-27'),
  ('shamir.shah@wearephlo.com',           'Shamir Shah',                 'Clinical Services Manager',                'Clinical',           '2023-09-11'),
  ('siobhan.amato@wearephlo.com',         'Siobhan Amato',               'People Operations Manager',                'People',             '2023-09-11'),
  ('sofiia.yevmenkina@wearephlo.com',     'Sofiia Yevmenkina',           'BD and AI Sales Intern',                   'Product',            null),
  ('sophia.barclay@wearephlo.com',        'Sophia Barclay',              'Patient Care Advisor',                     'Patient Care',       '2023-09-11'),
  ('stuart.noon@wearephlo.com',           'Stuart Noon',                 'IT Manager',                               'Technology',         '2023-05-22'),
  ('tam.thomas@wearephlo.com',            'Kwong Kuen Tam',              'Fulfilment Operative',                     'Fulfilment',         null),
  ('tamanna.somir@wearephlo.com',         'Tamanna Somir',               'Patient Services Dispenser',               'Patient Services',   '2024-08-05'),
  ('tashan.davis@wearephlo.com',          'Tashan Davis',                'Warehouse Operative',                      'Fulfilment',         '2025-04-07'),
  ('ting-hoi.chan@wearephlo.com',         'Ting-Hoi Chan',               'Pharmacy Governance Manager',              'Governance',         '2022-01-26'),
  ('tokolus.miah@wearephlo.com',          'Tokolus Miah',                'Fulfilment Operative',                     'Fulfilment',         '2025-06-23'),
  ('val.wells@wearephlo.com',             'Val Wells',                   'Head of People & Culture',                 'People',             '2026-01-05'),
  ('victoria.walker@wearephlo.com',       'Victoria Walker',             'Patient Care Advisor',                     'Patient Care',       '2026-04-27'),
  ('vladislavs.parols@wearephlo.com',     'Vladislavs Parols',           'Lead Clinical Technician',                 'Clinical',           '2024-07-15'),
  ('william.bayne@wearephlo.com',         'William Bayne',               'Senior Patient Care Advisor',              'Patient Care',       '2023-09-04'),
  ('yeekee.yan@wearephlo.com',            'Yee Kee Yan',                 'Pharmacy Dispenser',                       'Dispensary',         null),
  ('yolanda.valencia@wearephlo.com',      'Yolanda Valencia Munoz',      'Lead Prescribing Pharmacist',              'Clinical',           '2024-07-08'),
  ('zahraa.anwar@wearephlo.com',          'Zahraa Anwar',                'Pharmacist',                               'Dispensary',         null),
  ('zander.ellis@wearephlo.com',          'Alexander Ellis',             'Software Engineer 1',                      'Technology',         '2022-03-14')
on conflict (email) do update set
  display_name = excluded.display_name,
  title        = excluded.title,
  team         = excluded.team,
  start_date   = excluded.start_date,
  updated_at   = now();
